---
- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - clickhouse

- name: Install Vector
  hosts: vector
  roles:
    - vector-role

- name: Install Nginx & Lighthouse
  hosts: lighthouse
  roles:
     - lightHouse-role
