galaxy_info:
  author: Ivan Seleznev
  description: Vector role
  company: Netology
  license: MIT

  min_ansible_version: 2.8

  platforms:
  - name: CentOS
    versions:
    - 7
    - 8
 
  galaxy_tags: 
    - vector

dependencies: []
