---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 158.160.80.125
vector:
  hosts:
    vector-01:
      ansible_host: 158.160.81.148
lighthouse:
  hosts:
    lighthouse-01:
      ansible_host: 51.250.23.214

